image: git.stable.innovation.insee.eu:50000/innovation/rstudio

stages:
  - deploy

variables:
  GIT_SSL_NO_VERIFY: "1"
  PKG_NAME: "rtauargus"

pages:
  stage: deploy
  script:
    - R -e 'install.packages(c("gdata", "pkgdown"))'
    - R -e 'pkgdown::build_site()'
  artifacts:
    paths:
      - public
  when: manual # pour declencher manuellement le job quand version stable
  only:
    - master
