---
title: Package ‘rtauargus’
subtitle: Journal des modifications
output: rmarkdown::html_vignette
---

## rtauargus 0.3.1

[11/07/2019]

* informe de l'absence de tauargus.exe au chargement du package
* diverses améliorations de la documentation (rubriques d'aide et vignette)
* utilise valeurs par défaut des options en cas d'effacement accidentel par
  l'utilisateur

## rtauargus 0.3.0

[29/03/2019]

* **micro_arb()** :
    - ajoute paramètre apriori (fichiers hst)
    - conserve les noms de tabulations en sortie si précisés dans
      `explanatory_vars`
* vérification plus rigoureuse de certains paramètres

## rtauargus 0.2.1

[03/12/2018]

* **write_hrc()** : prise en compte de davantage de cas particuliers
* améliore vignette

## rtauargus 0.2.0

[14/08/2018]

* **micro_arb()** :
    - implémente tableaux liés (paramètre **linked**)
    - corrige extensions de fichiers pour `"5"` (.tab) et `"6"` (.jj)
    - corrige bug quand un seul paramètre à suppress, par exemple `MOD(1)`
* **write_hrc()** : nouvelle fonction  créant un fichier .hrc à partir de 
  variables hiérarchiques présentes dans les microdonnées 
* **micro_asc_rda()** :
    - implémente paramètres **missing**, **totcode** et **codelist**
    - simplifie syntaxe pour paramètre **hrc** (cohérente avec nouveaux
      paramètres)
    - nouveau paramètre **hierleadstring** (valeur par défaut dans l'option de
      package **rtauargus.hierleadstring**)
* efface les options du package à son déchargement
* corrections diverses documentation

## rtauargus 0.1.0

[01/08/2018]

* Première version stable.
