---
title: "TEST_SECRET"
output: html_document
date: "2023-08-03"
---

Le but de ce test est d'observer les différences de secret et de temps entre `split_tab = TRUE`
et `split_tab = FALSE` .


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Donnees 

```{r}
mon_chemin <- getwd()
library("sdcHierarchies")
library("stringr")
library("dplyr")
library("tictoc")
library("rtauargus")
loc_tauargus <- "Y:/Logiciels/TauArgus/TauArgus4.2.3/TauArgus.exe"
options(rtauargus.tauargus_exe = loc_tauargus)

devtools::load_all()

# Charge les fichiers

load("../data/ca_test_0_hrc.RData")
load("../data/test_4_var_1hrc.rda")

```


## Fonction pour poser le secret primaire 
```{r}
  data_sp <-function(data){
    data<-data %>% 
    mutate(
      is_secret_freq=(nb_obs > 0 & nb_obs < 3),
      is_secret_dom = (pizzas_tot != 0) & (pizzas_max > 0.85*pizzas_tot),
      pizzas_tot= round(abs(pizzas_tot),2)
    ) %>% 
    mutate(
      is_secret_prim =  is_secret_freq ,
      nb_obs = ceiling(nb_obs)
    )
    return(data)
  }
```

## Fonction calculant le secret 

```{r}
calculer_secret <- function(data, type = ""){
  if (is.logical(data$is_secret_final)) {
    data <- data %>% 
      mutate(
        statut_final = case_when(
          is_secret_freq ~ "A",
          is_secret_dom ~ "B",
          is_secret_final ~ "D",
          TRUE ~ "V"
        ))
  } else {
    data <- data %>% 
      mutate(
        statut_final = is_secret_final)}
    
  data %>% 
    group_by(statut_final) %>% 
    summarise(
      n_cell = n(),
      val_cell = sum(pizzas_tot)
    ) %>%
    mutate(
      pc_n_cell = round(n_cell/sum(n_cell)*100,1),
      pc_val_cell = round(val_cell/sum(val_cell)*100,1)
    ) %>% 
    mutate(METHODE = type) %>% 
    relocate(METHODE, .before = statut_final)
  
}
```

# TEST AVEC UNE TABLE A 4 DIMENSIONS ET 0 HIERARCHIES

## POSE DU SECRET PRIMAIRE

```{r }
data_0hrc <- data_sp(res_all_dtp)
```

```{r }
setwd("Z:/rtauargus")

masq_0hrc<-tab_rtauargus(
  data_0hrc,
  explanatory_vars = c("treff","cj","type_distrib","A10"),
  totcode = c(treff = "Total",cj = "Total",type_distrib = "Total",A10 = "Total"),
  secret_var = "is_secret_prim",
  value = "pizzas_tot",
  freq = "nb_obs",
  split_tab = FALSE
)

```

```{r}
setwd("Z:/rtauargus")

masq_0hrc_split<-tab_rtauargus(
  data_0hrc,
  explanatory_vars = c("treff","cj","type_distrib","A10"),
  totcode = c(treff = "Total",cj = "Total",type_distrib = "Total",A10 = "Total"),
  secret_var = "is_secret_prim",
  value = "pizzas_tot",
  freq = "nb_obs",
  split_tab = TRUE
)

```

# Comparaison des secret
```{r}
sec <- calculer_secret(masq_0hrc,"sans_split")
sec_split <- calculer_secret(masq_0hrc_split,"split")

```

# TEST AVEC UNE TABLE A 4 DIMENSIONS ET 1 HIERARCHIES


```{r }
data_1hrc <- data_sp(test_4_var_1hrc)
```

```{r }
masq_1hrc<-tab_rtauargus(
  data_1hrc,
  explanatory_vars = c("treff","cj","nuts1","A10"),
  totcode = c(treff = "Total",cj = "Total",nuts1 = "Total",ACTIVITY = "Total"),
  hrc = c(ACTIVITY="Z:/stage1A_2023/hrc/activity_2_niv.hrc"),
  secret_var = is_secret_prim,
  value = "pizzas_tot",
  freq = "nb_obs"
)
```

```{r}

masq_1hrc_split<-tab_rtauargus(
  data_1hrc,
  explanatory_vars = c("treff","cj","nuts1","A10"),
  totcode = c(treff = "Total",cj = "Total",nuts1 = "Total",ACTIVITY = "Total"),
  hrc = c(ACTIVITY="Z:/stage1A_2023/hrc/activity_2_niv.hrc"),
  secret_var = is_secret_prim,
  value = "pizzas_tot",
  freq = "nb_obs",
  split_tab = TRUE
)

```

