#' All in once for tabular
#'
#' @inheritParams tab_rda
#' @inheritParams tab_arb
#' @inheritParams run_arb
#'
#' @param files_name string used to name all the files needed to process.
#' All files will have the same name, only their extension will be different.
#' @param dir_name string indicated the path of the directory in which to save
#' all the files (.rda, .hst, .txt, .arb, .csv) generated by the function.
#' @param unif_labels boolean, if explanatory variables have to be standardized
#' @param ... any parameter of the tab_rda, tab_arb or run_arb functions, relevant
#' for the treatment of tabular.
#'
#' @return
#' If output_type equals to 4, then the original tabular is returned with a new
#' column called Status, indicating the status of the cell coming from Tau-Argus :
#' "A" for a primary secret due to frequency rule, "B" for a primary secret due
#' to dominance rule, "D" for secondary secret and "V" for no secret cell.
#'
#' If output_type doesn't equal to 4, then the raw result from tau-argus is returned.
#'
#' @section Standardization of explanatory variables and hierarchies:
#'
#' The boolean argument \code{unif_labels} is useful to
#' prevent some common errors in using Tau-Argus. Indeed, Tau-Argus needs that,
#' within a same level of a hierarchy, the labels have the same number of
#' characters. When the argument is set to TRUE, \code{tab_rtauargus}
#' standardizes the explanatory variables to prevent this issue.
#' Hierarchical explanatory variables (explanatory variables associated to
#' a hrc file) are then modified in the tabular data and an another hrc file is
#' created to be relevant with the tabular. In the output, these modifications
#' are removed.
#'
#' @examples
#'\dontrun{
#' library(dplyr)
#' library(stringr)
#'
#' # Compute the secondary secret ----
#' options(
#'   rtauargus.tauargus_exe =
#'     "Y:/Logiciels/TauArgus/TauArgus4.2.2b1/TauArgus.exe"
#' )
#'
#' # Reduce dims feature
#' load("donnees/ca_test_0_hrc.RData")
#'
#' res_all_dtp <- res_all_dtp %>%
#'   mutate(
#'     is_secret_freq = nb_obs > 0 & nb_obs < 3,
#'     is_secret_dom = ifelse(pizzas_max == 0, FALSE, pizzas_max/pizzas_tot>0.85),
#'     is_secret_prim = is_secret_freq | is_secret_dom,
#'     nb_obs = ceiling(nb_obs),
#'     pizzas_tot=abs(pizzas_tot)
#'   )
#'
#' res_dim4 <- tab_rtauargus4(
#'   tabular = res_all_dtp,
#'   files_name = "ca_test_0_hrc",
#'   dir_name = "ca_test_0_hrc",
#'   explanatory_vars = c("A10", "treff","type_distrib","cj"),
#'   totcode = c(A10 = "Total", treff = "Total",type_distrib = "Total",cj = "Total"),
#'   secret_var = "is_secret_prim",
#'   value = "pizzas_tot",
#'   freq = "nb_obs",
#'   verbose = TRUE,
#'   nb_tab = "min",
#'   verbose = TRUE
#' )
#'
#' # Do not run : it takes a lot of time !
#' load("donnees/test_5_var.RData")
#'
#' test_5_var <- test_5_var %>%
#'   mutate(
#'     is_secret_freq = nb_obs > 0 & nb_obs < 3,
#'     is_secret_dom = ifelse(pizzas_max == 0, FALSE, pizzas_max/pizzas_tot>0.85),
#'     is_secret_prim = is_secret_freq | is_secret_dom,
#'     nb_obs = ceiling(nb_obs),
#'     pizzas_tot=abs(pizzas_tot)
#'   )
#'
#' test_5_var$is_secret_prim %>% sum()
#'
#' res_dim5 <- tab_rtauargus4(
#'   tabular = test_5_var,
#'   files_name = "test_5_var",
#'   dir_name = "test_5_var",
#'   explanatory_vars = c("A10", "treff","type_distrib","cj","nuts1"),
#'   totcode = c(A10 = "Total", treff = "Total",type_distrib = "Total",cj = "Total",nuts1 = "Total"),
#'   secret_var = "is_secret_prim",
#'   value = "pizzas_tot",
#'   freq = "nb_obs",
#'   verbose = TRUE,
#'   nb_tab = "max",
#'   split_tab = TRUE,
#'   verbose = TRUE
#' )
#' }
#' @export
tab_rtauargus4 <- function(
    tabular,
    files_name = NULL,
    dir_name = NULL,
    explanatory_vars,
    totcode = getOption("rtauargus.totcode"),
    hrc = NULL,
    secret_var = NULL,
    secret_no_pl = NULL,
    cost_var = NULL,
    value = "value",
    freq = "freq",
    ip = 10,
    maxscore = NULL,
    suppress = "MOD(1,5,1,0,0)",
    safety_rules = paste0("MAN(",ip,")"),
    show_batch_console = FALSE,
    output_type = 4,
    output_options = "",
    unif_labels = TRUE,
    LIMIT = 14700,
    nb_tab = "smart",
    ...
){

  .dots <- list(...)

  # Reduce dims for 4 or 5 dimensions table
  if (length(explanatory_vars) %in% c(4, 5)) {

    cat("
Reducing dims...\n",files_name,"\n\n")

    list_tables <- reduce_dims(
      tab_to_split = tabular,
      nom_dfs = files_name,
      totcode = totcode,
      hrcfiles = hrc,
      hrc_dir = dir_name,
      nb_tab = nb_tab,
      LIMIT = LIMIT,
      split = TRUE,
      vec_sep = c("___"),
      verbose = TRUE
    )

    masq_list <- tab_multi_manager(
      list_tables = list_tables$tabs,
      list_explanatory_vars = list_tables$vars ,
      dir_name = dir_name,
      hrc = list_tables$hrc,
      totcode = list_tables$totcode,
      alt_hrc = list_tables$alt_hrc,
      alt_totcode = list_tables$alt_totcode,
      value = value,
      maxscore = maxscore,
      freq = freq,
      secret_var = secret_var,
      suppress = suppress
    )

    result <- restore_format(masq_list, list_tables)

    return(result)
  } else {
    stop("Do not use table with more than 5 dimensions. Split_tab = TRUE is not compatible with these large tables.")
  }
}
