
#' Title
#'
#' @inheritParams tab_rda
#' @inheritParams tab_arb
#' @inheritParams run_arb
#'
#' @param files_name string used to name all the files needed to process.
#' All files will have the same name, only their extension will be different.
#' @param dir_name string indicated the path of the directory in which to save
#' all the files (.rda, .hst, .txt, .arb, .csv) generated by the function.
#' @param ... any parameter of the tab_rda, tab_arb or run_arb functions, relevant
#' for the treatment of tabular.
#'
#' @return
#' AJOUTER TAG EXPORT à la fin
#'
#' @examples
#' 2+2
#' @export
tab_rtauargus <- function(
  tabular,
  files_name = NULL,
  dir_name = NULL,
  explanatory_vars = NULL,
  hrc            = NULL,
  totcode        = getOption("rtauargus.totcode"),
  secret_var = NULL,
  cost_var = NULL,
  value          = NULL,
  freq           = NULL,
  maxscore       = NULL,
  safety_rules = "MAN(10)",
  suppress = "MOD(1,5,1,0,0)",
  show_batch_console = FALSE,
  ...
){

  .dots <- list(...)

  ## 0. CONFLITS PARAMETRES .................

  # tabular not a data.frame
  if(!is.data.frame(tabular)){
    stop("tabular has to be a dataframe.")
  }

  ## 1. TAB_RDA  .....................

  # parametres
  param_tab_rda <- param_function(tab_rda, .dots)
  param_tab_rda$tabular <- tabular
  param_tab_rda$tab_filename <- file.path(dir_name, paste0(files_name, ".tab"))
  param_tab_rda$rda_filename <- file.path(dir_name, paste0(files_name, ".rda"))
  param_tab_rda$hst_filename <- if(is.null(secret_var) & is.null(cost_var)) NULL else file.path(dir_name, paste0(files_name, ".hst"))
  param_tab_rda$explanatory_vars <- explanatory_vars
  param_tab_rda$hrc <- hrc
  param_tab_rda$totcode <- totcode
  param_tab_rda$secret_var <- secret_var
  param_tab_rda$cost_var <- cost_var
  param_tab_rda$value <- value
  param_tab_rda$freq <- freq
  param_tab_rda$maxscore <- maxscore
  # appel (+ récuperation noms tab hst et rda)
  input <- do.call(tab_rda, param_tab_rda)


  ## 2. TAB_ARB .........................

  # parametres
  param_arb <- param_function(tab_arb, .dots)
  param_arb$tab_filename <- input$tab_filename
  param_arb$rda_filename <- input$rda_filename
  param_arb$hst_filename <- input$hst_filename
  param_arb$arb_filename <- file.path(dir_name, paste0(files_name, ".arb"))
  param_arb$output_names <- file.path(dir_name, paste0(files_name, ".csv"))
  #TODO : generaliser le choix de l'extension
  param_arb$explanatory_vars <- explanatory_vars
  param_arb$value <- value
  param_arb$safety_rules <- safety_rules
  param_arb$suppress <- suppress
  param_arb$show_batch_console <- show_batch_console

  # appel (+ récupération nom batch)
  batch <- do.call(tab_arb, param_arb)

  ## 3. RUN_ARB ...........................

  # parametres
  param_run0 <- param_function(run_arb, .dots)
  param_system <- param_function(system, .dots)
  param_run <- c(param_run0, param_system)
  param_run$arb_filename <- param_arb$arb_filename
  param_run$logbook <- file.path(dir_name, paste0(files_name, ".txt"))
  param_run$is_tabular <- TRUE

  # appel
  res <- do.call(run_arb, param_run)

  # RESULTAT .............................

  res

}
